---
layout: blog
topic: "01"
short-topic: Asking Good Questions
due-date: 2022-01-27
root: ../../
---

## Building a book:
Deliverable (1): the last word in Chapter 15 is class.

Deliverable (2): as I tried to build the book, I encoutered the following error:

Quitting from lines 4-5 (Introduction.Rmd) 
Error in dev.control(displaylist = if (record) "enable" else "inhibit") : 
  dev.control() called without an open graphics device
Calls: local ... call_block -> block_exec -> eng_r -> chunk_device -> dev.control
In addition: Warning messages:
1: In grSoftVersion() :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/modules//R_X11.so':
  dlopen(/Library/Frameworks/R.framework/Resources/modules//R_X11.so, 6): Library not loaded: /opt/X11/lib/libSM.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/modules/R_X11.so
  Reason: image not found
2: In cairoVersion() :
  unable to load shared object '/Library/Frameworks/R.framework/Resources/library/grDevices/libs//cairo.so':
  dlopen(/Library/Frameworks/R.framework/Resources/library/grDevices/libs//cairo.so, 6): Library not loaded: /opt/X11/lib/libXrender.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/grDevices/libs/cairo.so
  Reason: image not found
3: In (function (filename = if (onefile) "Rplots.pdf" else "Rplot%03d.pdf",  :
  failed to load cairo DLL
Execution halted
Error in Rscript_render(f, render_args, render_meta, add1, add2) : 
  Failed to compile Introduction.Rmd
Calls: local ... <Anonymous> -> render_new_session -> Rscript_render
Execution halted
Error: bookdown::render_book() failed to render the output format 'bookdown::pdf_book'.
Execution halted

Exited with status 1.

I read the warning message carefully, which told me that "Library not loaded: /opt/X11/lib/libSM.6.dylib", then I googled how to library X11 and I was told to install a software called "XQuartz", which can allow me to use run X11. After I installed this software, this issue was solved. 

## Weather stations:

 
 
 

 
 
 
 
 

